config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"

  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :description, presence: true
	validates :user_id, presence: true

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	belongs_to :user
	has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :pins
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
	  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]



  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
	<div class="container">
		<p class="navbar-text pull-left">Made with love by Sakshyam Dahal</p>	
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PinClone", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

      	<% if user_signed_in? %>
          <li><%= link_to "Add +", new_pin_path %></li>
      		<li><%= link_to "Edit profile", edit_user_registration_path %></li>
        	<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        	<li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		  <title>PininterestClone</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: 'alert alert-info') %>
		<% end %>

			<%= yield %>

			<%= render 'layouts/footer' %>
			</div>
	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
	<h1>You are logged in <%= current_user.name %>!!</h1>
<% else %>
	<div class="jumbotron">
		<h1>Welcome to Pininterest clone.</h1>
		<p>
			This is the home page for pininterest clone. I hope you enjoy the pins here.
			Thank you.
		</p>
		<p>
			<%= link_to "Sign up!!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	This is a about page.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>You are logged in <%= current_user.name %>!!</h1>
<% else %>
	<div class="jumbotron">
		<h1>Welcome to Pininterest clone.</h1>
		<p>
			This is the home page for pininterest clone. I hope you enjoy the pins here.
			Thank you.
		</p>
		<p>
			<%= link_to "Sign up!!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"} ) do |f| %>
  <%= f.error_notification %>

 
  <%= f.input :image, label: "Uplooad an image" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>
  

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= image_tag pin.image.url,size:"150x300" %>
	<p class="des">
    <%= pin.description %>
    </p>
    <p>
    <%= link_to 'Show', pin %>
    <% if current_user == pin.user %>
    <%= link_to 'Edit', edit_pin_path(pin) %>
    <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>
<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<div class="well">
			<%= image_tag @pin.image, size:"300x400"%>
			<p class="des">
			  <%= @pin.description %>
			</p>
			<p>
			  <%= @pin.user.name %>
			</p>
			<p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
			</p>
		</div>
	</div>
</div>